spring:
  dataSource:
    driverClass: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:

  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      show_sql: true
      format_sql: true
